export const EMAIL = 'EMAIL'
export const USERNAME = 'USERNAME'
export const PASSWORD = 'PASSWORD'
export const CONFIRM = 'CONFIRM'
export const MESSAGE = 'MESSAGE'
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP'
