export const EMAIL = 'EMAIL'
export const USERNAME = 'USERNAME'
export const PASSWORD = 'PASSWORD'
export const CONFIRM = 'CONFIRM'
export const MESSAGE = 'MESSAGE'
export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP'
export const SERVER_MESSAGE = 'SERVER_MESSAGE'
export const RESET_FIELDS = 'RESET_FIELDS'
export const CHANGE_FORM_TYPE = 'CHANGE_FORM_TYPE'

