export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const REQUEST_RESET = 'REQUEST_RESET'
export const PASSWORD_RESET = 'PASSWORD_RESET'
export const SIGNOUT = 'SIGNOUT'

export default [SIGNIN, SIGNUP, REQUEST_RESET, PASSWORD_RESET, SIGNOUT]
