export const ACCESSORY = 'ACCESSORY'
export const BEANIE = 'BEANIE'
export const HOODIE = 'HOODIE'
export const LONG_SLEEVE = 'LONG_SLEEVE'
export const SHIRT = 'SHIRT'
export const SHORTS = 'SHORTS'
