import React from 'react'

const CartIcon = ({ className, onClick }) => (
  <svg
    className={className}
    onClick={onClick}
    enableBackground="new 0 0 64 64"
    height="64px"
    id="Layer_1"
    version="1.1"
    viewBox="0 0 64 64"
    width="64px"
    xmlSpace="preserve"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink">
    <g>
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="19.8"
        x2="6.6"
        y1="48.8"
        y2="10.2"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="16.8"
        x2="47.3"
        y1="38.8"
        y2="38.8"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="19.8"
        x2="24.7"
        y1="48.8"
        y2="48.8"
      />
      <circle
        cx="29.7"
        cy="48.8"
        fill="none"
        r="5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
      />
      <circle
        cx="48.7"
        cy="48.8"
        fill="none"
        r="5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="35.6"
        x2="42.9"
        y1="48.8"
        y2="48.8"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="47.3"
        x2="55.9"
        y1="38.8"
        y2="23.9"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="12.2"
        x2="60.1"
        y1="23.9"
        y2="23.9"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="13.8"
        x2="50.9"
        y1="31.4"
        y2="31.4"
      />
      <circle
        cx="48.7"
        cy="48.8"
        fill="none"
        r="1.5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <circle
        cx="29.7"
        cy="48.8"
        fill="none"
        r="1.5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
      />
      <line
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeMiterlimit="10"
        strokeWidth="2"
        x1="6.6"
        x2="3.9"
        y1="10.2"
        y2="10.2"
      />
    </g>
  </svg>
)

export default CartIcon
