declare module 'styled-components'
declare module 'react-transition-group'
declare module 'uuid'
declare module 'react-responsive'
declare module 'react-helmet'
declare module 'isomorphic-fetch'
declare module '@nfront/global-styles'
declare module 'react-scroll'
declare module 'framer-motion'

// extensions
declare module '*.svg'
declare module '*.jpg'
declare module '*.png'
declare module '*.json'
